### ISSUE TITLE
Only use data from HSL Live HTTP interface if the socket interface does not provide any data

### ISSUE THREAD

**Issue by hannesj** [HSLdevcom/navigator-server#8]

**Comment by tpievila** [comment]
The poll interface doesn't have delay information, only location. Is this very useful? And is it even available when the push interface isn't? Needs to be tested.

**Comment by tuukka** [comment]
The location data is enough for displaying the vehicles on a map :-) or for making your own predictions. The type=nextstops request provides the delay information for a single vehicle (to the accuracy of minutes). But I wouldn't use much time on this issue: we can simply disable the HTTP polling.

**Comment by tuukka** [comment]
Disabled the interface, at least for now.
